# Generated by Django 5.1.1 on 2024-09-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=511)),
                ('status', models.CharField(choices=[('active', 'Active'), ('canceled', 'Inactive'), ('finalized', 'Finalized')], max_length=55)),
            ],
        ),
    ]
